[linux]
ubuntu ansible_host=192.168.56.4 ansible_user=hiba ansible_ssh_pass=ubuntu ansible_sudo_pass=ubuntu

[windows]
win10 ansible_host=192.168.56.5 ansible_user=Hiba ansible_password=123

[linux:vars]
ansible_python_interpreter=/usr/bin/python3

[windows:vars]
ansible_connection=winrm
ansible_port=5985
ansible_winrm_scheme=http
ansible_winrm_transport=basic
ansible_winrm_server_cert_validation=ignore
